
cache_dll=[
    "kernel32.dll_GetModuleHandleA",
    "kernel32.dll_LoadLibraryA",
    "kernel32.dll_GetProcAddress",
    "ntdll.dll_RtlInitializeCriticalSection",
    "kernel32.dll_GetCurrentThreadId",
    "kernel32.dll_OpenThread",
    "kernelbase.dll_OpenThread",
    "ntdll.dll_ZwOpenThread",
    "kernel32.dll_GetUserDefaultUILanguage",
    "kernel32.dll_GetProcessHeap",
    "kernelbase.dll_GetProcessHeap",
    "ntdll.dll_RtlAllocateHeap",
    "kernel32.dll_GetCurrentDirectoryW",
    "kernel32.dll_GetModuleFileNameW",
    "kernel32.dll_SetCurrentDirectoryW",
    "kernel32.dll_GetVersion",
    "kernelbase.dll_GetVersion",
    "ntdll.dll_SbSelectProcedure",
    "ntdll.dll_memset",
    "ntdll.dll_RtlGetVersion",
    "kernel32.dll_GetCommandLineA",
    "ntdll.dll_RtlAddVectoredExceptionHandler",
    "ntdll.dll_LdrControlFlowGuardEnforced",
    "ntdll.dll_RtlQueryProtectedPolicy",
    "ntdll.dll_ZwQueryInformationProcess",
    "ntdll.dll_RtlAcquireSRWLockExclusive",
    "ntdll.dll_RtlReleaseSRWLockExclusive",
    "kernel32.dll_VirtualAlloc",
    "kernelbase.dll_VirtualAlloc",
    "ntdll.dll_ZwAllocateVirtualMemory",
    "kernel32.dll_GetCurrentThread",
    "kernel32.dll_GetThreadContext",
    "kernelbase.dll_GetThreadContext",
    "ntdll.dll_ZwGetContextThread",
    "kernel32.dll_VirtualFree",
    "kernel32.dll_GetCurrentProcess",
    "kernelbase.dll_GetCurrentProcess",
    "kernel32.dll_CheckRemoteDebuggerPresent",
    "kernelbase.dll_CheckRemoteDebuggerPresent",
    "ntdll.dll_ZwSetInformationThread",
    "advapi32.dll_OpenThreadToken",
    "advapi32.dll_OpenProcessToken",
    "advapi32.dll_GetTokenInformation",
    "kernelbase.dll_GetTokenInformation",
    "ntdll.dll_ZwQueryInformationToken",
    "kernel32.dll_CloseHandle",
    "kernelbase.dll_CloseHandle",
    "ntdll.dll_ZwSetInformationProcess",
    "ntdll.dll_ZwClose",
    "advapi32.dll_AllocateAndInitializeSid",
    "kernelbase.dll_AllocateAndInitializeSid",
    "ntdll.dll_RtlAllocateAndInitializeSid",
    "advapi32.dll_FreeSid",
    "kernelbase.dll_FreeSid",
    "ntdll.dll_RtlFreeSid",
    "ntdll.dll_RtlFreeHeap",
    "shell32.dll_IsUserAnAdmin",
    "shell32.dll_SHTestTokenMembership",
    "kernelbase.dll_CheckTokenMembership",
    "ntdll.dll_RtlCheckTokenMembershipEx",
    "ntdll.dll_ZwOpenThreadTokenEx",
    "ntdll.dll_ZwOpenProcessTokenEx",
    "ntdll.dll_ZwDuplicateToken",
    "ntdll.dll_RtlCreateSecurityDescriptor",
    "ntdll.dll_RtlSetOwnerSecurityDescriptor",
    "ntdll.dll_RtlValidSid",
    "ntdll.dll_RtlValidAcl",
    "ntdll.dll_RtlFirstFreeAce",
    "ntdll.dll_RtlCopySid",
    "ntdll.dll_memmove",
    "ntdll.dll_RtlSetDaclSecurityDescriptor",
    "ntdll.dll_ZwAccessCheck",
    "kernel32.dll_VirtualProtect",
    "kernel32.dll_IsBadWritePtr",
    "ntdll.dll_ZwProtectVirtualMemory",
    "user32.dll_GetForegroundWindow",
    "win32u.dll_NtUserGetForegroundWindow",
    "user32.dll_GetWindowTextA",
    "kernel32.dll_RaiseException",
    "kernelbase.dll_RaiseException",
    "ntdll.dll_RtlRaiseException",
    "ntdll.dll_RtlGetExtendedContextLength2",
    "ntdll.dll___chkstk",
    "ntdll.dll_RtlInitializeExtendedContext2",
    "ntdll.dll_RtlLocateExtendedFeature2",
    "ntdll.dll_RtlLookupFunctionEntry",
    "ntdll.dll_RtlVirtualUnwind",
    "ntdll.dll_RtlRemoveVectoredExceptionHandler",
    "kernel32.dll_GetSystemFirmwareTable",
    "kernelbase.dll_GetSystemFirmwareTable",
    "ntdll.dll_ZwQuerySystemInformation",
    "ntdll.dll_RtlNtStatusToDosError",
    "ntdll.dll_RtlSetLastWin32Error",
    "advapi32.dll_RegOpenKeyA",
    "kernelbase.dll_RegOpenKeyExA",
    "advapi32.dll_RegQueryValueExA",
    "advapi32.dll_RegCloseKey",
]

hook_func={
    "kernel32.dll_GetModuleHandleA" : 0,
    "kernel32.dll_LoadLibraryA" : 1,
    "kernel32.dll_GetProcAddress" : 2,
    "ntdll.dll_ZwOpenThread" : 3,
    "kernel32.dll_GetUserDefaultUILanguage" : 4,
    "ntdll.dll_RtlAllocateHeap" : 5,
    "kernel32.dll_GetCurrentDirectoryW" : 6,
    "kernel32.dll_GetModuleFileNameW" : 7,
    "kernel32.dll_SetCurrentDirectoryW" : 8,
    "kernel32.dll_GetCommandLineA" : 9,
    "ntdll.dll_ZwQueryInformationProcess" : 10,
    "ntdll.dll_ZwAllocateVirtualMemory" : 11,
    "ntdll.dll_ZwGetContextThread" : 12,
    "kernel32.dll_VirtualFree" : 13,
    "ntdll.dll_ZwSetInformationThread" : 14,
    "advapi32.dll_OpenThreadToken" : 15,
    "advapi32.dll_OpenProcessToken" : 16,
    "ntdll.dll_ZwQueryInformationToken" : 17,
    "ntdll.dll_ZwSetInformationProcess" : 18,
    "ntdll.dll_ZwClose" : 19,
    "ntdll.dll_RtlFreeHeap" : 20,
    "ntdll.dll_ZwOpenThreadTokenEx" : 21,
    "ntdll.dll_ZwOpenProcessTokenEx" : 22,
    "ntdll.dll_ZwDuplicateToken" : 23,
    "ntdll.dll_ZwAccessCheck" : 24,
    "kernel32.dll_VirtualProtect" : 25,
    "win32u.dll_NtUserGetForegroundWindow" : 26,
    "user32.dll_GetWindowTextA" : 27,
    "ntdll.dll_ZwQuerySystemInformation" : 28,
    "kernelbase.dll_RegOpenKeyExA" : 29,
    "advapi32.dll_RegQueryValueExA" : 30,
    "advapi32.dll_RegCloseKey" : 31,
    "kernelbase.dll_VirtualProtect" : 32,
}